# Site settings
title: yjz
email: 934973079@qq.com
description: > # this means to ignore newlines until "baseurl:"
  manbaout
baseurl: /byrantYu.github.io
url: https://github.com/byrantYu
twitter_username: byrantYu
github_username:  byrantYu

# Build settings
markdown: kramdown
